// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20220819181935_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 2,
                            Breed = "Mini-Daschund",
                            Gender = "Male",
                            Name = "Henry",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 1,
                            Breed = "Mini-Daschund",
                            Gender = "Female",
                            Name = "Ellie",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 14,
                            Breed = "Beagle Bassett Hound",
                            Gender = "Male",
                            Name = "Cooper",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 4,
                            Breed = "Tuxedo",
                            Gender = "Female",
                            Name = "Sofie",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 3,
                            Breed = "American Shorthair",
                            Gender = "Male",
                            Name = "Maverick",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 5,
                            Breed = "Black Lab",
                            Gender = "Male",
                            Name = "George",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 7,
                            Breed = "Pomeranian",
                            Gender = "Female",
                            Name = "Feida",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 6,
                            Breed = "Cocker Spaniel",
                            Gender = "Female",
                            Name = "Lucy",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 3,
                            Breed = "Golden Retriever",
                            Gender = "Female",
                            Name = "Sally",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 8,
                            Breed = "Bulldog",
                            Gender = "Male",
                            Name = "Charlie",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 11,
                            Age = 2,
                            Breed = "Golden Doodle",
                            Gender = "Male",
                            Name = "Linus",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 12,
                            Age = 4,
                            Breed = "Munchkin",
                            Gender = "Male",
                            Name = "Boots",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 13,
                            Age = 3,
                            Breed = "Persian",
                            Gender = "Female",
                            Name = "Maire",
                            Species = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
